### ISSUE TITLE
Does this approach only capture prices at one (store) location?

### ISSUE THREAD

**Issue by JavascriptMick** [Javex/hotprices-au#15]
I have noticed on the Coles page, that you can set your location for e.g. click and collect.  I have also noticed that if you set your location to a different store, you get different prices for some items e.g. bananas.  Not surprising because location does affect availability of things in different locations.

I couldn't see anything in the code that attempts to set headers, cookies, request params etc that might attempt to gather prices from different store/locations.  Is this something you have attempted?

**Comment by Javex** [comment]
Yeah you're right @JavascriptMick , it's one fixed store: https://github.com/Javex/hotprices-au/blob/main/hotprices_au/sites/coles.py#L214

Based on the ID it might be this one: https://www.coles.com.au/find-stores/coles/vic/burwood-east-0584 but I'm not sure.

I vaguely recall doing a spot check and not seeing too much difference, but in the end the problem is more one of scale: If I'd want to scrape them for every store in the country it would explode and I don't wanna overload their servers, so for now I'm stuck with just one store. However, if you've got a specific one you want to start scraping, I could maybe make it configurable and then you can pick the Woolies & Coles you care about and set up your own Github Actions workflows?

**Comment by JavascriptMick** [comment]
Thanks for responding.  Ok, I see.  Yeah safe to say I'm knee deep in this one.  There are definitely price differences, in particular in the fresh produce, probably related to availability.

Pretty sure your use of the storeid only applies to the fetching of categories unless I missed something? the storeId only seems to make it into  ```self.session.get(f'https://www.coles.com.au/api/bff/products/categories?storeId={self.store_id}')```
and therefore doesn't really apply to the product fetching through the _next/data url.

I think that once you have selected a preferred store, store preference are probably associated with the session rather than in the parameters of the fetches.  
there are a bunch of cookies that look like maybe a session id
incap_ses_404_2800108
x-jsession-id
ai_session
x-jsession-id
sessionId
etc....

but I haven't figured out which one specifically 

If you have managed to figure out that relationship, would be interested to hear
